### ISSUE TITLE
Meltwater: KTLADT (CW) transcript not match (TRITON-25020)

### ISSUE THREAD

**Issue by ravibhojani-kinetiq** [iQMedia/tracker#101]
**Issue Creater Email:** Gloria Wan <gloria.wan@meltwater.com>

**Email Body:**
Hi Kinetiq

station: KTLADT (CW) - Los Angeles
KTLA 5 Morning News at 9 11-29-2024 9:00:00 AM PST

Clip from 9:45am is about
https://ktla.com/video/supporting-small-businesses-with-jenna-barnett/10258193/
but the transcript isn't available on the platform.

[image: Screenshot 2024-12-09 at 6.48.08 AM.png]
The clip we are looking for Millennial mom Jenna Barnett  is available at
`KTLA 5 Morning News at 9`

Can you please tell why the transcript is not available?

Thanks

Gloria

-- 

Disclaimer

The information contained in this email may be confidential. It has been sent for the sole use of the intended recipient(s). If the reader of this email is not an intended recipient, you are hereby notified that any unauthorized review, use, disclosure, dissemination, distribution, or copying of this message is strictly prohibited. If you have received this email in error, please notify the sender immediately and destroy all copies of the message.

For more information on how we process personal data please see www.meltwater.com/privacy. Please note that neither the Company nor the sender accepts any responsibility for viruses and it is your responsibility to scan or otherwise check this email and any attachments.

______________________________________________________________________
This email has been scanned by the Symantec Email Security.cloud service.
For more information please visit http://www.symanteccloud.com
______________________________________________________________________

______________________________________________________________________
This email has been scanned by the Symantec Email Security.cloud service.
For more information please visit http://www.symanteccloud.com
______________________________________________________________________

**Comment by amanvar21** [comment]
The caption was only partially ingested, the first 5 minutes to be exact. The clip was in a later part of the video hence, a transcript for the clip was not available.

Caption stitching was stuck, re-queuing the caption ingestion fixed it. Now, the full transcript is available and also contains the transcript for the clip mentioned.
