### ISSUE TITLE
Meltwater: Missing viewership (TRITON-25031)

### ISSUE THREAD

**Issue by ravibhojani-kinetiq** [iQMedia/tracker#104]
**Issue Creater Email:** Gloria Wan <gloria.wan@meltwater.com>

**Email Body:**
Hi Kinetiq

We received an enquiry about no viewership value for these stations.

sourceName:"CKNI-FM"
stationID: "CH12329"

sourceName:"CFRA-AM"
stationID: "CH12233"

sourceName:"CKSS-FM"
stationID: "CH12391

sourceName:"CFGO-AM"
stationID: "CH12394"

Please check.

Regards
Gloria

-- 

Disclaimer

The information contained in this email may be confidential. It has been sent for the sole use of the intended recipient(s). If the reader of this email is not an intended recipient, you are hereby notified that any unauthorized review, use, disclosure, dissemination, distribution, or copying of this message is strictly prohibited. If you have received this email in error, please notify the sender immediately and destroy all copies of the message.

For more information on how we process personal data please see www.meltwater.com/privacy. Please note that neither the Company nor the sender accepts any responsibility for viruses and it is your responsibility to scan or otherwise check this email and any attachments.

______________________________________________________________________
This email has been scanned by the Symantec Email Security.cloud service.
For more information please visit http://www.symanteccloud.com
______________________________________________________________________

______________________________________________________________________
This email has been scanned by the Symantec Email Security.cloud service.
For more information please visit http://www.symanteccloud.com
______________________________________________________________________

**Comment by BijalKinetiq** [comment]
These all are radio stations and we don't have viewership data for radio stations.
So closing this issue.
