### ISSUE TITLE
Gap in coverage - The Times Radio GBR (TRITON - 25251)

### ISSUE THREAD

**Issue by ravibhojani-kinetiq** [iQMedia/tracker#123]
**Issue Creater Email:** Chantelle Modiselle <chantelle.modiselle@meltwater.com>

**Email Body:**
Good Day Kinetiq

I hope this email finds you well.

We have noticed a gap in coverage for the broadcast channel *The Times
Radio GBR (CH12726)* between *16th December at 3 PM GMT* and *17th December
at 6 AM GMT*.

Could you kindly provide insight into the reason for this gap and confirm
if it is possible to backfill the missing coverage?

Thank you for your assistance, and I look forward to your response.

Kind regards

-- 

Disclaimer

The information contained in this email may be confidential. It has been sent for the sole use of the intended recipient(s). If the reader of this email is not an intended recipient, you are hereby notified that any unauthorized review, use, disclosure, dissemination, distribution, or copying of this message is strictly prohibited. If you have received this email in error, please notify the sender immediately and destroy all copies of the message.

For more information on how we process personal data please see www.meltwater.com/privacy. Please note that neither the Company nor the sender accepts any responsibility for viruses and it is your responsibility to scan or otherwise check this email and any attachments.

______________________________________________________________________
This email has been scanned by the Symantec Email Security.cloud service.
For more information please visit http://www.symanteccloud.com
______________________________________________________________________

______________________________________________________________________
This email has been scanned by the Symantec Email Security.cloud service.
For more information please visit http://www.symanteccloud.com
______________________________________________________________________

**Comment by aagam-kinetiqtv** [comment]
![image](https://github.com/user-attachments/assets/ede1c11e-1fab-4b0e-99bd-1798d5ae2264)

Closing this issue.
