### ISSUE TITLE
Radio Station Outage - BBC Essex

### ISSUE THREAD

**Issue by ravibhojani-kinetiq** [iQMedia/tracker#125]
**Issue Creater Email:** Christopher Smith <christopher.smith@meltwater.com>

**Email Body:**
Hi Kinetiq Folks,

We have noticed that the following radio station has not sent us any
content since beginning our partnership.

Name: BBC Essex
Market Name: U.K. Regional Radio
Country: GB
Call Sign: BBC Radio Essex 95.3FM GBR
SourceID: CH10711
Source: Radio

Would you be able to take a look and see why we aren't receiving any
content for that station ID? Thanks in advance!

*Christopher Smith*

Senior Product Support Engineer

christopher.smith@meltwater.com | app.meltwater.com

<https://www.meltwater.com/?utm_source=email&utm_medium=signature>

-- 

Disclaimer

The information contained in this email may be confidential. It has been sent for the sole use of the intended recipient(s). If the reader of this email is not an intended recipient, you are hereby notified that any unauthorized review, use, disclosure, dissemination, distribution, or copying of this message is strictly prohibited. If you have received this email in error, please notify the sender immediately and destroy all copies of the message.

For more information on how we process personal data please see www.meltwater.com/privacy. Please note that neither the Company nor the sender accepts any responsibility for viruses and it is your responsibility to scan or otherwise check this email and any attachments.

______________________________________________________________________
This email has been scanned by the Symantec Email Security.cloud service.
For more information please visit http://www.symanteccloud.com
______________________________________________________________________

______________________________________________________________________
This email has been scanned by the Symantec Email Security.cloud service.
For more information please visit http://www.symanteccloud.com
______________________________________________________________________

**Comment by BijalKinetiq** [comment]
![image](https://github.com/user-attachments/assets/9b2e8c30-7167-4020-937d-9cb224484bd2)

Closing Ticket.
