### ISSUE TITLE
Timeshift reporting hits on every word instead of the complete phrase

### ISSUE THREAD

**Issue by sergi0aranda** [iQMedia/tracker#130]
For a while, Timeshift has had this issue that when users search for a complete phrase, Timeshift does locate the hit correctly but when selecting the specific hour, the tool will report every single word as a "Search Term" and not the complete phrase.  As an example, I'm attaching two screenshots:

1) In the first one you can see I'm search for the phrase "until I found michaels"
![Screenshot 2024-12-21 at 9 07 37 AM](https://github.com/user-attachments/assets/85be82e2-5ef0-406b-a1fb-1194c8e3e332)

2) In the second one you can see the player opened showing a hit for every single word in the phrase, i.e. the close captioned on the left panel highlight every word, while the Search Term section down below also shows a hit a for every single word in the phrase when it should only be showing 1 hit for the complete phrase.
![Screenshot 2024-12-21 at 9 08 07 AM](https://github.com/user-attachments/assets/9b6788af-275e-40c2-8931-5d6a47d0708a)

Please correct this issue.

**Comment by aagam-kinetiqtv** [comment]
Hi @sergi0aranda ,
Issue has been fixed now. Can you please confirm?

**Comment by sergi0aranda** [comment]
Thanks @aagam-kinetiqtv , it is now fixed. confirmed.

**Comment by sergi0aranda** [comment]
Completed.
