### ISSUE TITLE
Sponsorship Module - Event Management file issue (2024-01-21 - Detroit Lions Divisional)

### ISSUE THREAD

**Issue by tkimiq** [iQMedia/tracker#19]
@Suhendro2017 @hollinger Could we look into this issue so I can report back to the client today?

The Lions 1/21/24 Divisional game is not showing up in the Sponsorship tab. Event file and screenshot included. I checked the columns for dupes or secondary market errors, but nothing tripped when uploading the CSV to Event Management. I initiated a backfill for 1/21-1/22 and still don't see any attribution even though in Timeshift and in IQPM (as well as Feeds in the Lions system), I'm seeing the tags and the completed hours.

[2024-01-21 - Buccaneers Divisional Round - Lions Divisional.csv](https://github.com/iQMedia/tracker/files/14541795/2024-01-21.-.Buccaneers.Divisional.Round.-.Lions.Divisional.csv)
![Screen Shot 2024-03-08 at 12 25 26 PM](https://github.com/iQMedia/tracker/assets/108010369/d93853c3-b08c-487f-a687-98a21252b471)
![Screen Shot 2024-03-08 at 12 34 11 PM](https://github.com/iQMedia/tracker/assets/108010369/721415e9-71df-4d44-9342-d25f406e8bc3)
![Screen Shot 2024-03-08 at 12 34 38 PM](https://github.com/iQMedia/tracker/assets/108010369/4afc4ade-1780-4c47-99d9-453a0da1352e)

**Comment by Suhendro2017** [comment]
Tayne,

I saw these in the iqsponsorshipevents table. One is Active, the other one
is inactive. I also see the corresponding data in
the IQSponsorshipEvent_Shows table. If they do not show up in the
dashboard, I have no idea.
[image: image.png]
[image: image.png]
