### ISSUE TITLE
Innovid: Occurrences file - DistinctMarkets equals 0 on Local DMAs (Non-National channels) and Distinct Market rows does not match with Distinct Market calculation

### ISSUE THREAD

**Issue by sergi0aranda** [iQMedia/tracker#3]
Innovid sent a number of questions but something we cannot explain is why are we reporting many rows with Distinct Markets = 0 (zero)when the Market fields is a local DMA, i.e.  Boise, Twin Falls, Denver, New York, etc. Meaning a detection in a non-National channel. I performed several checks and I'm seeing anything between 2 to 10% of the rows with this issue. 

As a sample, see the attached report with both Geico and McDonalds brands. You will note that of the 5,000 detections , 310 are Distinct Markets = 0 AND Market IS NOT National. Please advise why this is happening or whether this is an issue.
[sample_Occurrences_geico_mcdonalds.csv](https://github.com/iQMedia/tracker/files/9679585/sample_Occurrences_geico_mcdonalds.csv)

2022-10-03 UPDATE: Added another issue to to this ticket. 

Innovid has identified that the Distinct Markets number is not matching the number of rows (occurrences) for that ad around the same time. 

As an example, I'm submitting a file for Verizon ads, when filtering the excel file for ad AE16546-2022-37-09960 AND Distinct Markets = 186, you can see that only 182 hits and filtered.

**Comment by sergi0aranda** [comment]
Here is the Verizon file generated in ADDB.
[VerizonKinetiqFile.xlsx](https://github.com/iQMedia/tracker/files/9701678/VerizonKinetiqFile.xlsx)

**Comment by krmalladi** [comment]
@sergi0aranda : Distinct Markets column should only be referenced when isNational is True and the market is local. Do you see instances when Distinct markets is zero when isNational is True and the market is local?

**Comment by sergi0aranda** [comment]
Hi @krmalladi I'm not sure I agree with this...how about the cases where an ad is only seen in a few local markets? like when an ad is only seen in 3 or 5  or anything less than 60? Distinct Markets helps you find out in how many markets your ad ran.

**Comment by sergi0aranda** [comment]
Closing ticket as Dragos indicated that this Distinct Markets should not be exposed externally. It is still an internal issue and should be addressed in the future.
