### ISSUE TITLE
OTT Live content needs to include keywords.

### ISSUE THREAD

**Issue by robertweerts87** [iQMedia/tracker#30]
OTT playout should always be done based on the keywords that are in the system. 
So whether it is: 

**Prio 1**		-      Live E.g. Live football match between RB Leipzig vs. Bayen Munich at 4 p.m.

**Prio 2**		-      Re-Live (definition: same broadcast as Live but at a later moment in time. Replay/Restart TV) E.g. Football match between RB Leipzig vs. Bayen Munich  but played out 2 hours after live. 6 p.m.

**Prio 2**		-      Recaps (definition: summary and/or highlights of a game/match/race) E.g. Summary and highlights of the football match between RB Leipzig vs. Bayen Munich. 

**Prio 2** 		-      Magazines (definition: highlights of a competition or tournament) Summary and highlights of the Bundesliga games from that day/weekend. 

**Prio 2** 		-      Specials (definition: a documentary about a Xavi Simons (player from RB Leipzig).

All content should be based on the keywords. So if there is no match on keywords, we don’t need to playout anything. 
What remains the same. Live is still a higher priority than the others.

**Comment by zalak-kinetiqtv** [comment]
Initiating task

**Comment by zalak-kinetiqtv** [comment]
Deployed for ESPN+ and Discovery+
