### ISSUE TITLE
Create export buttons in https://ott-control.kinetiq.tv

### ISSUE THREAD

**Issue by rasveld** [iQMedia/tracker#31]
1. Red Bull is requesting to receive a regular overview of historic as well as future planned live events. This would be possible in case an "Export to Excel" button would become available on https://ott-control.kinetiq.tv/live-events
The export should export the result values form the Filter.
![image](https://github.com/iQMedia/tracker/assets/20574860/d3f2ba29-0abf-4475-908f-06cd563b975d)

2. Red Bull is requesting to receive a regular overview of Video's Played.  This would be possible in case an "Export to Excel" button would become available on https://ott-control.kinetiq.tv/videos-played
The export should export the result values form the Filter.
![image](https://github.com/iQMedia/tracker/assets/20574860/01797ec4-af23-4703-bb36-ac79ca0da75a)

**Comment by zalak-kinetiqtv** [comment]
Initiating task

**Comment by zalak-kinetiqtv** [comment]
Deployed
