### ISSUE TITLE
WGRZ No Audio

### ISSUE THREAD

**Issue by tkimiq** [iQMedia/tracker#38]
TRuescope reports no audio from WGRZ from 3/23 and 3/31

![image (18)](https://github.com/iQMedia/tracker/assets/108010369/b48116e3-614f-4910-be35-84843f9251ab)

**Comment by ken-kinetiq** [comment]
yeah, I have no idea how to respond to a GitHub ticket, sorry.

Audio has returned, and I have no idea why it was missing, and have no
record of initiating it's return.

`Ken

Ken Przywara
Kinetiq.tv
p. 267-898-0691
c. 302-584-8377
www.kinetiq.tv
