### ISSUE TITLE
Innovid:  Found a few instances where Market = National AND isNational = '0' (False)

### ISSUE THREAD

**Issue by sergi0aranda** [iQMedia/tracker#4]
Innovid found some channels where Market = National AND isNational = '0' (False), this is a combination that should not be happening.

This is happening for the following channels:

**ChannelName	          ChannelResourceID**
ACC Network	                            CH04788
Antenna TV	                            CH03147
Bally Sports Kansas City	   CH02262
BT Sport 1	                            CH03223
CNN International	                    CH00006
DW-TV	                                    CH02773
ESPN Mexico	                            CH03468
Fox Sports Mexico	                   CH03467
Globo TV Internacional	           CH00780
SEC Network	                            CH03906

Please let us know if you have any questions on this issue.

**Comment by krmalladi** [comment]
Please can you add some example data that shows this issue? Note that the isNational logic takes unto 36 hours to update, so if Innovid is pulling data within that period, data might not be consistent

**Comment by sergi0aranda** [comment]
Yes, my mind went to the 36 hours when Innovid told me about this issue. But it happens with old occurrences too. Attached is a small sample and below is the script that will give you the 9 channels with this problem.
[National_channels_isNational_False.xlsx](https://github.com/iQMedia/tracker/files/9716373/National_channels_isNational_False.xlsx)

SELECT top 100 ChannelName, ChannelResourceID from dbo.v_ADDBOccurrences t1 
INNER JOIN IQTTX.dbo.ADDBCreatives t2 on t1.AssetResourceID = t2.ResourceID
WHERE t1.ClientID = '16546' AND 
t1.Market = 'National' AND 
t1.IsNational = '0'  AND 
t1.LocalStartDateTime BETWEEN  '2022-09-15' AND '2022-09-20'
GROUP By ChannelName, ChannelResourceID

**Comment by sergi0aranda** [comment]
Updating this ticket as this issue will also be re-surfaced by Comscore, here's the output of the query above:
ChannelName	      ChannelResourceID
ACC Network	      CH04788
Antenna TV	      CH03147
Bally Sports Kansas City	CH02262
BT Sport 1	      CH03223
CNN International	CH00006
DW-TV	CH02773
ESPN Mexico	CH03468
Fox Sports Mexico	CH03467
Globo TV Internacional	CH00780
QVC	CH09971
SEC Network	CH03906

**Comment by sergi0aranda** [comment]
Hi @krmalladi @Suhendro2017, I opened the ticket in TTX but this issue is right on the TTX DB side. It is not correct on the data coming from ADDB tool. I believe we should correct (at least four channels) from National to Regional, these are: ACC Network (CH04788), Antenna TV (CH03147), Bally Sports Kansas City (CH02262), SEC Network (CH03906). See more details in the attached.

**Comment by sergi0aranda** [comment]
Updating this ticket to Feb 2024 as several customers have complained about this issue. Probably moving this ticket to Teletrax github as this logic is controlled on their end. Below are the 16 stations that are reporting this same issue as of Feb 2024:

<google-sheets-html-origin><style type="text/css"></style>
ChannelName | ChannelResourceID | IsNational | Market
-- | -- | -- | --
ACC Network | CH04788 | 0 | National
Antenna TV | CH03147 | 0 | National
Bally Sports Kansas City | CH02262 | 0 | National
ESPN Mexico | CH03468 | 0 | National
Fox Sports Mexico | CH03467 | 0 | National
Globo TV Internacional | CH00780 | 0 | National
Marquee Sports Network | CH08393 | 0 | Regional
MASN | CH02271 | 0 | Regional
NBC Sports Boston | CH02257 | 0 | Regional
NBC Sports California | CH02276 | 0 | Regional
NBC Sports Chicago | CH02269 | 0 | Regional
NBC Sports Philadelphia | CH02296 | 0 | Regional
NBC Sports Washington | CH04103 | 0 | Regional
SEC Network | CH03906 | 0 | National
Space City Home Network | CH02306 | 0 | Regional
SportsNet Pittsburgh | CH02263 | 0 | Regional

**Comment by sergi0aranda** [comment]
Closing ticket as this has been moved to Teletrax github.

**Comment by sergi0aranda** [comment]
closing.
