### ISSUE TITLE
Search and registration of live events need to be done from a different category for Discovery+ Germany

### ISSUE THREAD

**Issue by robertweerts87** [iQMedia/tracker#42]
Live events are currently registered from the wrong place. They are taken from the "Top-Auswahl" which doens't contain all live events. 

As per attached image this would be the correct order to find the complete sports-related schedule. 

![image](https://github.com/iQMedia/tracker/assets/98310012/b3d2405d-6381-496b-afb3-902f6f3ebbb0)

**Comment by zalak-kinetiqtv** [comment]
Task initiated.

**Comment by zalak-kinetiqtv** [comment]
Implemented and deployed.
