### ISSUE TITLE
Priorities should always be taken from Search Keywords page. 

### ISSUE THREAD

**Issue by robertweerts87** [iQMedia/tracker#44]
All live events should be registered based on the priority givin to the keyword on the Search Keywords page. 

We should be able to change it in case we want to, occasionally.
With the remark that LIVE is always more important than  NON-LIVE.

So a Live event with prio 4 is still more important than non-live prio 1. 

Next to this, If two live events overlap, the one with the highest priority should be played. Regardless of the starting times. 

If we have two events that overlap with the same priority, then a decision based on starting time could be made.

**Comment by zalak-kinetiqtv** [comment]
Implemented
