### ISSUE TITLE
Change behavior of "Show xx entries"

### ISSUE THREAD

**Issue by robertweerts87** [iQMedia/tracker#46]
It is annoying to go through all entries from the UI every time you add/delete something. 

Example: 
![image](https://github.com/iQMedia/tracker/assets/98310012/4e0bcf22-e65f-4664-bf39-f04a95945664)
Just changed the amount of items displayed from 10 --> 25. 
Whenever there is 1 entry deleted or added, the UI jumps back to the original view with 10 entries and on page 1.

**Comment by zalak-kinetiqtv** [comment]
Changes has been deployed
