### ISSUE TITLE
Entitlements NLogic DEMO Account (Canada)

### ISSUE THREAD

**Issue by sergi0aranda** [iQMedia/tracker#52]
Jordan, for the NLogic Demo account, please grant entitlements as follows:

16846 - Canada EN
16857 - Canada FR
16546 - US Only the following markets:

Seattle - DMA 13: KCPQ, KING, KIRO, KOMO
Buffalo - DMA 54: WGRZ, WIVB, WKBW, WUTV

This is a large opportunity for us so please prioritize accordingly. Let me know if you have any questions.

**Comment by hollinger** [comment]
Entitlements have been added for the above regions and stations

**Comment by sergi0aranda** [comment]
Thanks @hollinger , I'm not finding Canadian brands/creatives (16846 or 16857) in the Ad Catalog. See screenshot. You can test it using the following login: admin@nlogic.ca, the password in the standard one for admins. A good example is to look for Tim Hortons which is a typical Canadian brand. I'm just not seeing any Canadian creatives in the Catalog.
![Screenshot 2024-06-14 at 4 21 53 PM](https://github.com/iQMedia/tracker/assets/107960104/880578bb-ebab-4c24-a945-c360cbe505e4)

**Comment by hollinger** [comment]
User error on my part with adding the additional regions. It is fixed now, and I confirmed that I can see Canadian brands/creatives with that login.

**Comment by sergi0aranda** [comment]
Done and done.
