### ISSUE TITLE
ADDB Ad hoc jobs - "File is not available to download" error (Innovid)

### ISSUE THREAD

**Issue by sergi0aranda** [iQMedia/tracker#55]
hi @jmylet , I had already noticed this issue but did nothing about it and now is affecting customers.

What happened:

1) Innovid created ad hoc job 5815 for Platform Download.

2) When you go to Job Status and try to Download the file, you get the following error message:

<img width="1440" alt="Screenshot 2024-06-27 at 2 56 16 PM" src="https://github.com/iQMedia/tracker/assets/107960104/dcc6339f-0aa3-4e84-aec0-332f9c2e8cf5">

3) The Status of the job is `COMPLETED`

4) I do see     `TotalResults": 19173` hits for this Brand (DoorDash) in April2024: 

"AirDateStartUtc": "2024-04-01T00:00",
"AirDateEndUtc": "2024-05-01T00:00",
"BrandIDs": ["MF16546-001-O19643"],

**Comment by jmylet** [comment]
This issue is confined to any ADHOC job for a platform download that gets processed by the file delivery service recently deployed to IQMPRADB01 in the past week, likely due to an incorrectly configured drive mounted to this server.

**Comment by jmylet** [comment]
Fixed the required directory mount for platform downloads on IQMPRADB01.
