### ISSUE TITLE
Search exclusions for live content. 

### ISSUE THREAD

**Issue by robertweerts87** [iQMedia/tracker#56]
Please add the option for search exclusion on live content and/or on-demand content.
Maybe build some checkbox to select on which content? 

In addition to the above. It would be great to have the option "If title contains keyword". 

Example: 

3 titles starting at same time. only required title contains "Siegerehrung". 

Search keyword: Tour de France

Search exclusion keyword: Breakaway
Search exclusion keyword: Velo Club

Titles:

_Tour de France | 13. Etappe mit "The Breakaway"_
**Tour de France | 13. Etappe mit Siegerehrung**
_Tour de France | 13. Etappe mit "Velo Club"_

**Comment by zalak-kinetiqtv** [comment]
OTT automation application for discovery plus has been deployed. 
OTT control application will deploy soon to operate search exclusion feature from UI.

**Comment by aagam-kinetiqtv** [comment]
This feature has been deployed
