### ISSUE TITLE
Found 10 inactive channels that are reporting detections

### ISSUE THREAD

**Issue by sergi0aranda** [iQMedia/tracker#6]
The following channels are inactive in iq_Station table BUT are reporting hits:

Channel Name 	Station ID	Channel Resource ID
KFWD	                  KFWD	         CH01437
KQCA	                  KQCA	         CH00216
KSMO	                  KSMO	         CH00809
WDSI	                  WDSI	         CH00856
WDFX	                  WDFX	         CH01534   
WDHN	                  WDHN	         CH01533
WTVY	                   WTVY	         CH01531
Galavision	           XEQ	         CH01086
Universal Kids	           SPRO	         CH02670
Bally Sports Oklahoma	FSOK	CH02311
     

As an example in the screenshot below you can see occurrences reported by Galavision | XEQ | CH01086

![Screen Shot 2022-09-30 at 11 15 03 AM](https://user-images.githubusercontent.com/107960104/193332386-d0c16eeb-b4a1-4f13-8cc2-9a9a488ab615.png)

This issue prevents the sales team from knowing whether the channels are available or not for occurrences reporting?

**Comment by Suhendro2017** [comment]
I updated the records in the IQ_Station table. They are active now.
