### ISSUE TITLE
Meltwater: Cannot preview/play radio clips (TRITON-24746)

### ISSUE THREAD

**Issue by ravibhojani-kinetiq** [iQMedia/tracker#78]
**Issue Creater Email:** Gloria Wan <gloria.wan@meltwater.com>

**Email Body:**
Hi Kinetiq

Radio clips do not have any content when played. Redirecting to the Kinetiq
link shows nothing. See more notes in the ticket regarding affected Stations

Clip shows nothing, explains why the preview is not showing:
https://iqmediacorp.com/ExternalIframeMedia?AU=ECD95E6E4A7A0A3B1578ACF1892A1765C9FF5C08F85224B26E412C9991B98D59C8156046DD73B133F1593839B1B7A2B914931687410CD35B8D9EA4DB981EB4858DE30CCDEBCC1E77AC9E1B2631ADFBA4D2883573D1B4D0E6F04FEB91CE9DCBCC92E882B5756F144AC862AD24092415D40AE7406A434EC656D1E0D5D9EB89FA5B8F1B0A396E835DDCF20ACABF60F08A7DC3FFFC37&mediaID=77373713-95ab-4791-a1c1-65c91538ef8e&RawMediaType=Radio&startOffset=1800&endOffset=2400&SessionID=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJhcGlAbWVsdHdhdGVyLmNvbSIsIlVzZXJDbGllbnQiOiI5YWJmZjA4Zi1mOGY2LTQwY2YtYTliOS1iMGQ5ZjNjZDQ0ZWEiLCJDdXN0b21lckdVSUQiOiIwMTExODE4Yy00Y2UwLTQyODMtOGEwNy1iOGFhZGI3MzUyM2EiLCJDdXN0b21lcktleSI6IjEwNTE0IiwiQ2xpZW50SUQiOiIxNTk1IiwiVXNlcktleSI6IjE4OTJjOWI4NzJhYjE0MDFlZGU0NTZhZjBjZTdjYjFkZGY0NDdlZjk3MzEzOTQyMzk0ZTg5OTg2MTJhMzZmMTkiLCJJUVJvbGVzIjpbInY0QVBJIiwidjRUViIsInY0RmVlZHMiLCJ2NFJhZGlvIiwidjRMaWJyYXJ5IiwidjRJUUFnZW50U2V0dXAiLCJ2NUxSIiwidjREYXNoYm9hcmQiLCJOaWVsc2VuRGF0YSIsIkNvbXBldGVEYXRhIiwidjVBZHMiLCJDQ1RleHRBY2Nlc3MiLCJBRERCRGF0YSIsIk1lZGlhQ29udGVudEFjY2VzcyIsIkV4dGVybmFsQ2xpcENyZWF0aW9uIiwiaXNBdWRpZW5jZU1lZGlhVmFsdWVWaXNpYmxlIiwiUG9kY2FzdCIsIkFEREJUcmFuc2NyaXB0cyJdLCJuYmYiOjE3MzI2Mzk0OTQsImV4cCI6MTczMjgxMjI5NCwiaXNzIjoiSVFQbGF0Zm9ybUFQSSIsImF1ZCI6IklRUGxhdGZvcm1BUEkifQ.UkUzTfmi1wn9EhfA1U583taHR1Gu0C96WFHnJS1IRl4&SearchQuery=CHED-AM%20-%20Thu%20OR%20%2021%20Nov%202024%2008:30:00&HighlightQuery=CHED-AM%20-%20Thu%20OR%20%2021%20Nov%202024%2008:30:00&QueryPreroll=15&EnableClipDownload=true

This clip does play a preview and opens fine when clicking on the link:
https://iqmediacorp.com/ExternalIframeMedia?AU=7E2CF818765719F66A677113678A23DE6C8C04C1DBEBC38A7BFE92BCB01DC78E2B2515B74E93B89A294C468C05B9A13BFEB3C1F5C0A6A1F847A1D8A5EB19A8697190770F5DA197A6653EB0317CA8F4D4E77D4D4F0C73BB0EDD59ED47DB244CD35BB9DC51DA6D6A7B84DE9BA7BAE95B8050EECB4840EBDEEEAB19D60A9C252C99207DE8654566641F20AC33F7C985723F12395CCC&mediaID=32513b7d-745c-4ada-874a-7d5b25884e4c&RawMediaType=Radio&startOffset=1800&endOffset=2400&SessionID=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJhcGlAbWVsdHdhdGVyLmNvbSIsIlVzZXJDbGllbnQiOiI5YWJmZjA4Zi1mOGY2LTQwY2YtYTliOS1iMGQ5ZjNjZDQ0ZWEiLCJDdXN0b21lckdVSUQiOiIwMTExODE4Yy00Y2UwLTQyODMtOGEwNy1iOGFhZGI3MzUyM2EiLCJDdXN0b21lcktleSI6IjEwNTE0IiwiQ2xpZW50SUQiOiIxNTk1IiwiVXNlcktleSI6IjE4OTJjOWI4NzJhYjE0MDFlZGU0NTZhZjBjZTdjYjFkZGY0NDdlZjk3MzEzOTQyMzk0ZTg5OTg2MTJhMzZmMTkiLCJJUVJvbGVzIjpbInY0QVBJIiwidjRUViIsInY0RmVlZHMiLCJ2NFJhZGlvIiwidjRMaWJyYXJ5IiwidjRJUUFnZW50U2V0dXAiLCJ2NUxSIiwidjREYXNoYm9hcmQiLCJOaWVsc2VuRGF0YSIsIkNvbXBldGVEYXRhIiwidjVBZHMiLCJDQ1RleHRBY2Nlc3MiLCJBRERCRGF0YSIsIk1lZGlhQ29udGVudEFjY2VzcyIsIkV4dGVybmFsQ2xpcENyZWF0aW9uIiwiaXNBdWRpZW5jZU1lZGlhVmFsdWVWaXNpYmxlIiwiUG9kY2FzdCIsIkFEREJUcmFuc2NyaXB0cyJdLCJuYmYiOjE3MzI2Mzk0MjEsImV4cCI6MTczMjgxMjIyMSwiaXNzIjoiSVFQbGF0Zm9ybUFQSSIsImF1ZCI6IklRUGxhdGZvcm1BUEkifQ.ldkQITixDE-XaTK9UX_AtF1eXUVggcSKbGuhhf6i3wM&SearchQuery=edmonton%20public%20schools&HighlightQuery=edmonton%20public%20schools&QueryPreroll=15&EnableClipDownload=true

Please let us know if more info is needed.

Regards
Gloria

-- 

Disclaimer

The information contained in this email may be confidential. It has been sent for the sole use of the intended recipient(s). If the reader of this email is not an intended recipient, you are hereby notified that any unauthorized review, use, disclosure, dissemination, distribution, or copying of this message is strictly prohibited. If you have received this email in error, please notify the sender immediately and destroy all copies of the message.

For more information on how we process personal data please see www.meltwater.com/privacy. Please note that neither the Company nor the sender accepts any responsibility for viruses and it is your responsibility to scan or otherwise check this email and any attachments.

______________________________________________________________________
This email has been scanned by the Symantec Email Security.cloud service.
For more information please visit http://www.symanteccloud.com
______________________________________________________________________

______________________________________________________________________
This email has been scanned by the Symantec Email Security.cloud service.
For more information please visit http://www.symanteccloud.com
______________________________________________________________________

**Comment by ravibhojani-kinetiq** [comment]
**New Reply from Gloria Wan [gloria.wan@meltwater.com](mailto:gloria.wan@meltwater.com)**

Hi Gloria,

Could you clarify what browser is being used? I'm on Chrome and was able to play both radio clips back. Please let me know if this issue persists and I'll escalate this asap.

Thanks,
Tayne

**Comment by BijalKinetiq** [comment]
Gloria confirmed, this issue was resolved on 28th Nov
